name: Team 1 ArgoCD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/argocd

    - name: Authenticate with ArgoCD
      env:
        ARGOCD_SERVER: <your-argocd-server-url>
        ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
      run: |
        argocd login $ARGOCD_SERVER \
          --username admin \
          --password $ARGOCD_TOKEN \
          --insecure

    - name: Sync Team 1 Application
      run: |
        argocd app sync team1-app
